# Generated by Django 4.2.16 on 2024-12-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='round',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
