# Generated by Django 4.2.16 on 2024-12-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_validanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='validation_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
