# Generated by Django 4.2.16 on 2025-01-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_submission_validation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
