# Generated by Django 4.2.16 on 2024-12-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_category_options_round_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category')),
            ],
            options={
                'unique_together': {('category', 'word')},
            },
        ),
    ]
