# Generated by Django 5.1.3 on 2025-02-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_address_remove_user_phone_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('avatar1.gif', 'Avatar 1'), ('avatar2.gif', 'Avatar 2'), ('avatar3.gif', 'Avatar 3')], default='avatar1.gif', max_length=100),
        ),
    ]
