# Generated by Django 4.2.7 on 2025-02-10 22:05

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_address_remove_user_phone_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_avatar_upload_path),
        ),
    ]
